nginx:
    build: ./nginx
    container_name: ms_nginx
    links:
        - petstore
        - users
    ports:
        - "80:80"

petstore:
    build: ./petstore
    container_name: ms_petstore
    links:
        - "mongo:mongo"
    volumes:
        - "./petstore:/src/app"
    working_dir: "/src/app"
    ports:
        - "5858:5858"
    command: npm start

users:
    build: ./users
    container_name: ms_users
    links:
        - neo4j
    volumes:
        - "./users:/src/app"
    working_dir: "/src/app"
    command: npm start

mongo:
    container_name: ms_mongo
    image: mongo:latest
    environment:
        - loglevel=1
    ports:
        - "27017:27017"

neo4j:
    container_name: ms_neo4j
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
